import type { Metadata } from "next";

export const metadata: Metadata = { title: "Terms of Service — DataPilot AI" };

export default function TermsPage() {
  return (
    <main className="container-app py-16 max-w-3xl">
      <h1 className="text-3xl font-bold mb-8">Terms of Service</h1>
      <div className="prose prose-neutral max-w-none space-y-6 text-sm leading-relaxed">
        <p><em>Last updated: {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</em></p>

        <h2 className="text-xl font-semibold mt-8">1. Acceptance</h2>
        <p>By using DataPilot AI, you agree to these Terms of Service. If you do not agree, please do not use our service.</p>

        <h2 className="text-xl font-semibold mt-8">2. Service Description</h2>
        <p>DataPilot AI provides automated data analysis services including statistical analysis, data visualization, and AI-generated insights for CSV and Excel files.</p>

        <h2 className="text-xl font-semibold mt-8">3. Important Disclaimers</h2>
        <p>DataPilot AI is an analytical assistant. It does not guarantee business outcomes. AI-generated insights may contain errors or inaccuracies. Users remain solely responsible for any decisions made based on reports or insights generated by DataPilot AI.</p>
        <p>DataPilot AI is not a trading platform, investment advisor, financial signal service, or gambling platform.</p>

        <h2 className="text-xl font-semibold mt-8">4. User Responsibilities</h2>
        <p>You are responsible for the files you upload and must have the right to process that data. You must not upload files containing malicious content.</p>

        <h2 className="text-xl font-semibold mt-8">5. Subscriptions & Payments</h2>
        <p>Paid subscriptions are processed through Polar. You may cancel at any time; access continues until the end of the current billing period.</p>

        <h2 className="text-xl font-semibold mt-8">6. Limitation of Liability</h2>
        <p>DataPilot AI shall not be liable for any indirect, incidental, or consequential damages arising from use of the service.</p>

        <h2 className="text-xl font-semibold mt-8">7. Changes</h2>
        <p>We may update these terms from time to time. Continued use constitutes acceptance of updated terms.</p>
      </div>
    </main>
  );
}
