from fastapi import APIRouter, Depends, HTTPException, Request
from pydantic import BaseModel
from app.core.auth import get_current_user, get_user_id
from app.core.config import settings
import httpx

router = APIRouter(prefix="/api/notifications", tags=["notifications"])


class EmailRequest(BaseModel):
    to: str
    subject: str
    html: str


class AnalysisCompleteEmail(BaseModel):
    analysis_id: str
    file_name: str
    rows: int
    columns: int
    quality_score: int


@router.post("/analysis-complete")
async def send_analysis_complete(
    data: AnalysisCompleteEmail,
    user: dict = Depends(get_current_user),
):
    """Send email when analysis is complete. Uses any SMTP/email service."""
    user_id = get_user_id(user)
    email = user.get("email", "")

    if not email:
        raise HTTPException(status_code=400, detail="No email found")

    html = f"""
    <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto;">
      <div style="background: #4f46e5; color: white; padding: 24px; border-radius: 12px 12px 0 0;">
        <h1 style="margin: 0; font-size: 20px;">DataPilot AI</h1>
      </div>
      <div style="padding: 24px; border: 1px solid #e5e7eb; border-top: none; border-radius: 0 0 12px 12px;">
        <h2 style="margin: 0 0 16px;">Your analysis is ready!</h2>
        <p style="color: #52525b; margin: 0 0 16px;">
          Your analysis of <strong>{data.file_name}</strong> has been completed.
        </p>
        <div style="background: #f9fafb; padding: 16px; border-radius: 8px; margin-bottom: 16px;">
          <p style="margin: 4px 0; color: #52525b;">Rows: <strong>{data.rows:,}</strong></p>
          <p style="margin: 4px 0; color: #52525b;">Columns: <strong>{data.columns}</strong></p>
          <p style="margin: 4px 0; color: #52525b;">Quality Score: <strong>{data.quality_score}/100</strong></p>
        </div>
        <a href="{settings.frontend_url}/dashboard/analyses/{data.analysis_id}"
           style="display: inline-block; background: #4f46e5; color: white; padding: 12px 24px; border-radius: 8px; text-decoration: none; font-weight: 500;">
          View Results
        </a>
      </div>
      <p style="color: #a1a1aa; font-size: 12px; text-align: center; margin-top: 16px;">
        Generated by DataPilot AI
      </p>
    </div>
    """

    # Here you would integrate with your email provider
    # Examples: SendGrid, Resend, Postmark, or SMTP
    # For now, we log the email content
    print(f"[EMAIL] To: {email}, Subject: Your DataPilot AI analysis is ready")

    return {"status": "sent", "to": email}
